spring.application.name=discovery-service

eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443

# Disable self-preservation (prevents Render free tier issues)
eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000
# Rate limiter
eureka.server.rate-limiter-enabled=false

server.port=8761
