spring.application.name=AUTH-SERVICE

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=${RENDER_HOSTNAME:localhost}
eureka.instance.non-secure-port-enabled=false
eureka.instance.secure-port-enabled=true
eureka.instance.secure-port=443
eureka.instance.lease-renewal-interval-in-seconds=90
eureka.instance.lease-expiration-duration-in-seconds=270
eureka.client.registry-fetch-interval-seconds=120
eureka.client.eureka-server-connect-timeout-seconds=10
eureka.client.eureka-server-read-timeout-seconds=10
eureka.client.num-eureka-notify-replicas=0


#Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/auth_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:hrhk4321}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG

#server port
server.port = 8081
